name: vdict_service
dependencies:
- mysql-python=1.2.5=py27_0
- openssl=1.0.2d=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.7.0=py27_0
- sqlite=3.9.2=0
- system=5.8=2
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - django==1.9.5
  - django-cors-headers==1.1.0
  - django-filter==0.13.0
  - django-sslserver==0.19
  - djangorestframework==3.3.3
  - markdown==2.6.6

